Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -48,11 +48,20 @@ jobs:
       run: |
         mkdir -p Tool-repo/AdguardHome/Rules
 
-        curl -L -o Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/HTTPDNS.Block.list"
+        > Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt
+        urls=(
+          "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/HTTPDNS.Block.list"
+        )
+
+        for url in "${urls[@]}"; do
+          echo "Downloading: $url"
+          curl -f -L -H "Accept-Language: en-us" "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
+        done
 
         for file in Tool-repo/AdguardHome/Rules/*.txt; do
           if [ "$file" = "Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt" ]; then
-            sed -i -e '/^IP-CIDR,/d' -e '/^IP-CIDR6,/d' -e 's/[[:space:]]//g' "$file"
+            #sed -i -e '/^IP-CIDR,/d' -e '/^IP-CIDR6,/d' -e '/^URL-REGEX,/d' -e '/^URL-REGEX,/d' -e 's/[[:space:]]//g' -e '/^[[:space:]]*$/d' "$file"
+            sed -i -e 's/[[:space:]]//g' -e '/^[[:space:]]*$/d' "$file"
             sort -t, -k2,2 -u "$file" -o "$file"
             awk -F, '
               /^DOMAIN(-SUFFIX)?,/ {
