Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -56,7 +56,7 @@ jobs:
 
         for url in "${urls[@]}"; do
           echo "Downloading: $url"
-          curl -f -L -A "Loon/770 CFNetwork/1410.0.3 Darwin/22.6.0" -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-us" "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
+          curl -v -L -A "Loon/770 CFNetwork/1410.0.3 Darwin/22.6.0" -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-us" "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
           echo "" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt
         done
 
