Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -49,9 +49,10 @@ jobs:
     - name: Install curl-impersonate
       run: |
         mkdir -p $HOME/bin
-        curl -L -o $HOME/bin/curl-impersonate \
-          https://github.com/lwthiker/curl-impersonate/releases/latest/download/curl-impersonate
-        chmod +x $HOME/bin/curl-impersonate
+        curl -L -o $HOME/bin/curl-impersonate-chrome \
+          https://github.com/lwthiker/curl-impersonate/releases/latest/download/curl-impersonate-chrome
+        chmod +x $HOME/bin/curl-impersonate-chrome
+        ln -s $HOME/bin/curl-impersonate-chrome $HOME/bin/curl-impersonate
         echo "$HOME/bin" >> $GITHUB_PATH
 
     - name: AdguardHome Rules
@@ -66,7 +67,7 @@ jobs:
 
         for url in "${urls[@]}"; do
           echo "Downloading: $url"
-          curl-impersonate -v -f -L --impersonate safari15_3 -H "User-Agent: Loon/883 CFNetwork/1410.0.3 Darwin/22.6.0" -H "Accept: */*" -H "Connection: keep-alive" -H "Accept-Language: zh-CN,zh-Hans;q=0.9" --compressed "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
+          curl-impersonate-chrome -v -f -L --impersonate safari15_3 -H "User-Agent: Loon/883 CFNetwork/1410.0.3 Darwin/22.6.0" -H "Accept: */*" -H "Connection: keep-alive" -H "Accept-Language: zh-CN,zh-Hans;q=0.9" --compressed "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
           echo "" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt
         done
 
