Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -51,11 +51,12 @@ jobs:
         > Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt
         urls=(
           "https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/HTTPDNS.Block.list"
+          "https://kelee.one/Tool/Loon/Lpx/Block_HTTPDNS.lpx"
         )
 
         for url in "${urls[@]}"; do
           echo "Downloading: $url"
-          curl -f -L -H "Accept-Language: en-us" "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
+          curl -f -L -A "Surge iOS/3367" -H "Accept-Language: en-us" "$url" >> Tool-repo/AdguardHome/Rules/HTTPDNS.Block.txt || { echo "Download Failed: $url"; exit 1; }
         done
 
         for file in Tool-repo/AdguardHome/Rules/*.txt; do
